### ISSUE TITLE
An error occurred while using the plugin.

### ISSUE THREAD

**Issue by dfdfdfs** [OsOmE1/Beebyte-Deobfusctator#1]
An error occurs while using the plugin. 
![0000мок](https://user-images.githubusercontent.com/24856424/103124968-9134da00-469a-11eb-815c-23d5639b9a5c.PNG)

In the unobfuscated global-metadata.dat line, I indicated the path to the apk version without obfuscation.

What should be specified in the GameAsembly.dll line?

I specified the path to the Assembly-CSharp.dll unfustered version of the apk.

![Снимок](https://user-images.githubusercontent.com/24856424/103125315-ba099f00-469b-11eb-9542-ec53199e79d8.PNG)

Then I throw the obfuscated apk into the program and get an error.

**Comment by OsOmE1** [comment]
This doesn’t work for apks yet

**Comment by dfdfdfs** [comment]
Ok bro. I answered in discord.
